//! @generated by `scripts/resolve-registry-pins.sh` — DO NOT EDIT BY HAND.
//!
//! Build-time-resolved pins for the shared infra the account resolves in
//! `apply_doc`, cached here so normal builds are **offline and deterministic**
//! (no registry/network access, no `stellar` plugin). Regenerate with
//!
//! ```sh
//! scripts/resolve-registry-pins.sh   # needs stellar-registry-cli + network
//! ```
//!
//! which runs `stellar registry fetch-contract-id` / `fetch-hash` against the
//! `unverified/perch/stateless` subregistry on **testnet** and rewrites this file
//! (re-running with an unchanged registry produces an identical file). Review the
//! diff like any other change: because the hashes are **pinned** (not fetched at
//! runtime), a deployed account only ever uses the wasm resolved here, so a later
//! republish in the registry cannot change its behavior — the
//! `installed == reviewed` guarantee holds, and this file is what "reviewed"
//! means for the infra. The content addresses these pins derive to are asserted
//! against the live testnet deployment in
//! `crates/integration-tests/tests/testnet_pins.rs`.

/// `stellar registry fetch-contract-id unverified/perch/stateless`
pub const STATELESS_REGISTRY: &str = "CC6ELNH6YVRRO4WIETIURY3PZLD7NHSDXHRMTJQUT7D733SYVQFYB26O";

// `stellar registry fetch-hash unverified/perch/stateless/perch-doc-compiler`
perch_registry_resolve::registry_contract! {
    mod: compiler,
    wasm_name: "perch-doc-compiler",
    client: perch_doc_compiler::DocCompilerClient,
    hash: "3645bd0de34f4896c5e6fd8ca141713eb9f8658728bf16d82026418d4ab0b27f",
}

// `stellar registry fetch-hash unverified/perch/stateless/perch-interpreter`
// (address-only: the interpreter is used solely as a rule's policy-map key)
perch_registry_resolve::registry_contract! {
    mod: interpreter,
    wasm_name: "perch-interpreter",
    hash: "f8320d3031e7dffe51fac14177c5353b8818f8e6df3bda6c4c1b714f5ce1d858",
}
