use super::*;
use perch_recovery_interface::zk::DOM_AUTH;

/// 32 bytes whose big-endian halves are the field elements `hi` and `lo`.
fn halves(e: &Env, hi: u8, lo: u8) -> BytesN<32> {
    let mut b = [0u8; 32];
    b[15] = hi;
    b[31] = lo;
    BytesN::from_array(e, &b)
}

fn small(e: &Env, v: u8) -> BytesN<32> {
    let mut b = [0u8; 32];
    b[31] = v;
    BytesN::from_array(e, &b)
}

fn field(v: u8) -> [u8; 32] {
    let mut b = [0u8; 32];
    b[31] = v;
    b
}

fn hex(e: &Env, s: &str) -> BytesN<32> {
    BytesN::from_array(e, &hex32(s))
}

/// The same inputs `circuits/perch_zk/src/tests.nr::parity_vectors` hashes
/// with noir-lang/poseidon, and the same expected outputs it asserts. A
/// mismatch on either side means host and circuit disagree, and no proof
/// generated by the circuit will verify against values the contracts compute.
#[test]
fn parity() {
    let e = Env::default();
    let mut h = Hasher::new(&e);
    assert_eq!(
        h.node(&small(&e, 1), &small(&e, 2)),
        hex(
            &e,
            "038682aa1cb5ae4e0a3f13da432a95c77c5c111f6f030faf9cad641ce1ed7383"
        )
    );
    assert_eq!(
        h.commitment(&small(&e, 3)),
        hex(
            &e,
            "301d7a7973f3ec9c92ebc8afa9855b49aef4ba8c7c67fb64fae99fac8992dfa0"
        )
    );
    assert_eq!(
        h.leaf(&halves(&e, 4, 5), &halves(&e, 6, 7), &small(&e, 8)),
        hex(
            &e,
            "241225f632b43077765a98b79d36e32782272c95b46b8a2c9275bfd0ac551d1c"
        )
    );
    assert_eq!(
        h.nullifier(&halves(&e, 9, 10), &halves(&e, 11, 12), &small(&e, 13)),
        hex(
            &e,
            "1ffa05820357fd280b04acdf157da0a4481feefec252476b44fc702b77902b8c"
        )
    );
    let fields = ZkStatementFields {
        account_hi: field(14),
        account_lo: field(15),
        enrollment_hi: field(16),
        enrollment_lo: field(17),
        digest_hi: field(18),
        digest_lo: field(19),
    };
    assert_eq!(fields.auth_preimage()[0], DOM_AUTH);
    assert_eq!(
        h.statement_hash(&fields),
        hex(
            &e,
            "17d4bf97cdbb6037d073d98b2e87f37039e7db0927c2be8b2f46c668b15f3cf7"
        )
    );
    assert_eq!(
        h.zero_hashes(32).get_unchecked(32),
        hex(
            &e,
            "0b59baa35b9dc267744f0ccb4e3b0255c1fc512460d91130c6bc19fb2668568d"
        )
    );
}

#[test]
fn zero_hash_table_matches_recomputation() {
    let e = Env::default();
    let mut h = Hasher::new(&e);
    let computed = h.zero_hashes(MAX_TREE_DEPTH);
    for (i, z) in ZERO_HASHES.iter().enumerate() {
        assert_eq!(computed.get_unchecked(i as u32).to_array(), *z, "level {i}");
    }
}

#[test]
fn only_contract_addresses_have_a_contract_id() {
    use soroban_sdk::testutils::Address as _;
    let e = Env::default();
    assert!(contract_id(&e, &Address::generate(&e)).is_some());
    let account = Address::from_str(
        &e,
        "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    );
    assert!(contract_id(&e, &account).is_none());
}
