#!/usr/bin/env bash
# Regenerate packages/perch-contracts from a deployment manifest:
#
#   src/<module>.ts     `stellar contract bindings typescript` of the exact
#                       wasm the manifest names (fetched by address and
#                       hash-checked by scripts/fetch-infra-wasm.sh --stack)
#   src/deployments.ts  the manifest itself, typed
#
# Each generated module records the sha256 of the wasm it came from, and the
# package's tests fail if that or deployments.ts drifts from the manifest.
#
# Usage: scripts/bindings-contracts.sh [deployments/testnet.json]
#        scripts/bindings-contracts.sh --undeployed <stack-dir> <module>...
#
# --undeployed regenerates only the named modules from a stack built from
# source (scripts/build-stack.sh), for a contract change that is not
# deployed yet. Those modules export `DEPLOYED = false`, the package's tests
# skip their manifest check, and the next deployment's regeneration
# replaces them.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
pkg="$repo_root/packages/perch-contracts"

contract_of() {
    case "$1" in
        account) echo perch-account ;;
        factory) echo perch-account-factory ;;
        recovery) echo perch-recovery ;;
        pool) echo perch-zk-pool ;;
        adapter) echo perch-zk-adapter ;;
        webauthn-verifier) echo perch-webauthn-verifier ;;
        doc-compiler) echo perch-doc-compiler ;;
        *) echo "unknown module: $1" >&2; exit 1 ;;
    esac
}

if [ "${1:-}" = "--undeployed" ]; then
    stack="$2"
    shift 2
    [ $# -gt 0 ] || { echo "usage: $0 --undeployed <stack-dir> <module>..." >&2; exit 1; }
    out="$(mktemp -d)"
    trap 'rm -rf "$out"' EXIT
    for module in "$@"; do
        contract="$(contract_of "$module")"
        hash="$(jq -r --arg c "$contract" '.artifacts[] | select(.package == $c) | .sha256' "$stack/build.json")"
        stellar contract bindings typescript --wasm "$stack/${contract//-/_}.wasm" \
            --output-dir "$out/$module" --overwrite >/dev/null
        {
            printf '%s\n' \
                "// GENERATED FILE — do not edit by hand." \
                "//" \
                "// TypeScript client bindings for $contract, generated by" \
                "// \`stellar contract bindings typescript\` from a stack built from" \
                "// source (scripts/build-stack.sh), not from a deployment: no deployment" \
                "// runs this interface yet. The next deployment's" \
                "// scripts/bindings-contracts.sh run replaces this file." \
                "" \
                "/** sha256 of the wasm these bindings were generated from. */" \
                "export const WASM_SHA256 = \"$hash\";" \
                "" \
                "/** These bindings describe a build no deployment runs yet. */" \
                "export const DEPLOYED = false;" \
                ""
            cat "$out/$module/src/index.ts"
        } >"$pkg/src/$module.ts"
        echo "  src/$module.ts  ($contract $hash, undeployed)" >&2
    done
    exit 0
fi

manifest="${1:-$repo_root/deployments/testnet.json}"
network="$(jq -r .network "$manifest")"
stack="$repo_root/target/stack-$network"

"$repo_root/scripts/fetch-infra-wasm.sh" --manifest "$manifest" --stack "$stack"

# module  contract
MODULES="account:perch-account
factory:perch-account-factory
recovery:perch-recovery
pool:perch-zk-pool
adapter:perch-zk-adapter
webauthn-verifier:perch-webauthn-verifier
doc-compiler:perch-doc-compiler"

out="$(mktemp -d)"
trap 'rm -rf "$out"' EXIT
while IFS=: read -r module contract; do
    wasm="$stack/${contract//-/_}.wasm"
    hash="$(jq -r --arg c "$contract" '.contracts[$c].sha256' "$manifest")"
    stellar contract bindings typescript --wasm "$wasm" --output-dir "$out/$module" --overwrite >/dev/null
    {
        cat <<EOF
// GENERATED FILE — do not edit by hand.
//
// TypeScript client bindings for $contract, generated by
// \`stellar contract bindings typescript\` from the wasm deployed in
// deployments/$network.json. Regenerate with scripts/bindings-contracts.sh.

/** sha256 of the wasm these bindings were generated from. */
export const WASM_SHA256 = "$hash";

EOF
        cat "$out/$module/src/index.ts"
    } >"$pkg/src/$module.ts"
    echo "  src/$module.ts  ($contract $hash)" >&2
done <<<"$MODULES"

{
    cat <<EOF
// GENERATED FILE — do not edit by hand. Regenerate with
// scripts/bindings-contracts.sh from deployments/$network.json.

import type { Deployment } from "./deployment.js";

EOF
    printf 'export const %s: Deployment = ' "$network"
    jq . "$manifest"
    echo ';'
} >"$pkg/src/deployments.ts"
echo "  src/deployments.ts" >&2
