#!/usr/bin/env bash
# Resolve the perch infra pins from the registry and (re)generate the committed
# cache at crates/perch-smart-account/src/registry_pins.rs.
#
# This is the ONLY place network/registry access enters the account build: normal
# builds compile the committed registry_pins.rs offline. Run this only to refresh
# the pins (new infra version, redeployed stateless registry), then review the
# diff and commit — the file is what `installed == reviewed` means for the infra.
#
# Requires: the Stellar CLI + registry plugin (`cargo install stellar-registry-cli`)
# and network access to the target network's RPC.
#
# Config via env (defaults target testnet):
#   STELLAR_NETWORK          network name passed to the CLI (default: testnet)
#   PERCH_STATELESS_NAME     the stateless subregistry's registry name
#   PERCH_COMPILER_WASM      compiler wasm name (Prefixed, routes to the registry)
#   PERCH_INTERPRETER_WASM   interpreter wasm name (Prefixed)
set -euo pipefail

STELLAR_NETWORK="${STELLAR_NETWORK:-testnet}"
export STELLAR_NETWORK
STATELESS_NAME="${PERCH_STATELESS_NAME:-unverified/perch/stateless}"
COMPILER_WASM="${PERCH_COMPILER_WASM:-unverified/perch/stateless/perch-doc-compiler}"
INTERPRETER_WASM="${PERCH_INTERPRETER_WASM:-unverified/perch/stateless/perch-interpreter}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/crates/perch-smart-account/src/registry_pins.rs"

command -v stellar >/dev/null || {
  echo "error: 'stellar' CLI not found. Install it, then 'cargo install stellar-registry-cli'." >&2
  exit 1
}

# --- Resolve from the registry ------------------------------------------------
echo "resolving pins from '$STELLAR_NETWORK' ..." >&2
stateless_id="$(stellar registry fetch-contract-id "$STATELESS_NAME" | tr -d '[:space:]')"
compiler_hash="$(stellar registry fetch-hash "$COMPILER_WASM" | tr -d '[:space:]')"
interpreter_hash="$(stellar registry fetch-hash "$INTERPRETER_WASM" | tr -d '[:space:]')"

# --- Validate -----------------------------------------------------------------
[[ "$stateless_id" =~ ^C[A-Z2-7]{55}$ ]] || { echo "error: bad stateless id: '$stateless_id'" >&2; exit 1; }
[[ "$compiler_hash" =~ ^[0-9a-f]{64}$ ]] || { echo "error: bad compiler hash: '$compiler_hash'" >&2; exit 1; }
[[ "$interpreter_hash" =~ ^[0-9a-f]{64}$ ]] || { echo "error: bad interpreter hash: '$interpreter_hash'" >&2; exit 1; }

# --- Emit (must match the committed format byte-for-byte) ---------------------
cat > "$out" <<EOF
//! @generated by \`scripts/resolve-registry-pins.sh\` — DO NOT EDIT BY HAND.
//!
//! Build-time-resolved pins for the shared infra the account resolves in
//! \`apply_doc\`, cached here so normal builds are **offline and deterministic**
//! (no registry/network access, no \`stellar\` plugin). Regenerate with
//!
//! \`\`\`sh
//! scripts/resolve-registry-pins.sh   # needs stellar-registry-cli + network
//! \`\`\`
//!
//! which runs \`stellar registry fetch-contract-id\` / \`fetch-hash\` against the
//! \`unverified/perch/stateless\` subregistry on **testnet** and rewrites this file
//! (re-running with an unchanged registry produces an identical file). Review the
//! diff like any other change: because the hashes are **pinned** (not fetched at
//! runtime), a deployed account only ever uses the wasm resolved here, so a later
//! republish in the registry cannot change its behavior — the
//! \`installed == reviewed\` guarantee holds, and this file is what "reviewed"
//! means for the infra. The content addresses these pins derive to are asserted
//! against the live testnet deployment in
//! \`crates/integration-tests/tests/testnet_pins.rs\`.

/// \`stellar registry fetch-contract-id $STATELESS_NAME\`
pub const STATELESS_REGISTRY: &str = "$stateless_id";

// \`stellar registry fetch-hash $COMPILER_WASM\`
perch_registry_resolve::registry_contract! {
    mod: compiler,
    wasm_name: "perch-doc-compiler",
    client: perch_doc_compiler::DocCompilerClient,
    hash: "$compiler_hash",
}

// \`stellar registry fetch-hash $INTERPRETER_WASM\`
// (address-only: the interpreter is used solely as a rule's policy-map key)
perch_registry_resolve::registry_contract! {
    mod: interpreter,
    wasm_name: "perch-interpreter",
    hash: "$interpreter_hash",
}
EOF

echo "wrote $out" >&2
echo "  stateless   = $stateless_id" >&2
echo "  compiler    = $compiler_hash" >&2
echo "  interpreter = $interpreter_hash" >&2
echo "next: review the diff, run 'cargo test -p perch-integration-tests --test testnet_pins', commit." >&2
