#!/usr/bin/env python3
"""Independent reference implementation of the per-rule canonical hash.

Writes testdata/rule-hashes.json from the committed CANON v1 fixtures
(testdata/*.canonical.json), following CANONICAL.md "Fragment hashes":

    rule_hash = SHA-256("perch/rule" || R)

where R is exactly the bytes one rule contributes to the document's
canonical serialization: one element of the top-level "rules" array, without
the separating commas. The rule bytes are cut out of the committed canonical
documents by a bracket scanner that honours JSON strings, never re-serialized,
so this implementation shares no code with perch-ir's emitter. The Rust tests
(crates/perch-recovery-interface/tests/vectors.rs) assert every vector.

Usage: python3 scripts/rule-hash-vectors.py
"""

import hashlib
import json
import os

RULE_DOMAIN = b"perch/rule"
FIXTURES = ["ci-publish", "ci-publish-delegated", "ci-publish-threshold"]


def top_level_elements(text, start):
    """Split the JSON array whose '[' is at text[start] into the exact source
    substrings of its elements. Returns (elements, index after ']')."""
    assert text[start] == "["
    elements, depth, in_str, esc, elem_start = [], 0, False, False, start + 1
    i = start
    while True:
        c = text[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c in "[{":
            depth += 1
        elif c in "]}":
            depth -= 1
            if depth == 0:
                if i > elem_start:
                    elements.append(text[elem_start:i])
                return elements, i + 1
        elif c == "," and depth == 1:
            elements.append(text[elem_start:i])
            elem_start = i + 1
        i += 1


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = {
        "_comment": "Generated by scripts/rule-hash-vectors.py from testdata/*.canonical.json per CANONICAL.md 'Fragment hashes'. Do not edit by hand.",
        "domain": RULE_DOMAIN.decode(),
        "fixtures": [],
    }
    for name in FIXTURES:
        with open(os.path.join(root, "testdata", f"{name}.canonical.json"), "rb") as f:
            raw = f.read()
        text = raw.decode("utf-8")
        key = '"rules":['
        assert text.count(key) == 1, name
        rules, _ = top_level_elements(text, text.index(key) + len(key) - 1)
        entries = []
        for i, r in enumerate(rules):
            rb = r.encode("utf-8")
            entries.append(
                {
                    "index": i,
                    "name": json.loads(r)["name"],
                    "canonical": r,
                    "rule_hash": hashlib.sha256(RULE_DOMAIN + rb).hexdigest(),
                }
            )
        out["fixtures"].append(
            {
                "fixture": f"testdata/{name}.canonical.json",
                "doc_hash": hashlib.sha256(raw).hexdigest(),
                "rules": entries,
            }
        )
    path = os.path.join(root, "testdata", "rule-hashes.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(path)


if __name__ == "__main__":
    main()
