//! Guards the **account's actual shipped pins** (`perch_smart_account::registry_pins`,
//! generated by `scripts/resolve-registry-pins.sh`) against the live testnet
//! deployment. Binds testnet's network id and asserts that the pinned
//! `STATELESS_REGISTRY` + wasm hashes derive the exact content-addressed ids that
//! are live on testnet — so a bad regeneration (or a drifted pin) fails CI here.
//! Also cross-checks that the pinned stateless id equals `name-salt(perch
//! registry, "stateless")`, the base `deploy` convention.
use perch_registry_resolve::registry_contract;
use perch_smart_account::registry_pins::{compiler, interpreter, STATELESS_REGISTRY};
use soroban_sdk::testutils::Ledger;
use soroban_sdk::{Address, Bytes, Env};

/// The perch registry (`unverified/perch`) on testnet — used to cross-check that
/// the pinned stateless id is exactly `name-salt(perch registry, "stateless")`.
const PERCH_REGISTRY: &str = "CASB2M4JQSGP3QHFBGK5U6DGJXJX34GX37C2JFBU73LKKDXXNNIZHCP7";

// The stateless subregistry, resolved from the perch registry by name-salt — the
// derivation the account's pinned `STATELESS_REGISTRY` must agree with.
registry_contract! {
    mod: stateless,
    deploy_name: "stateless",
}
// The verifier is content-addressed too, but the account doesn't resolve it
// (docs name it directly); pinned here only to guard its live id.
registry_contract! {
    mod: verifier,
    wasm_name: "perch-ed25519-verifier",
    client: perch_ed25519_verifier::PerchEd25519VerifierClient,
    hash: "6ddf7cadcb85059cffa5b127f994490ee560f8a46b2bb437975fbe5bd0cc7de4",
}

#[test]
fn account_pins_derive_the_deployed_testnet_addresses() {
    let env = Env::default();
    // Bind to Stellar testnet's network id — address derivation is a function of
    // (network_id, registry, salt=wasm_hash).
    let net = env
        .crypto()
        .sha256(&Bytes::from_slice(
            &env,
            b"Test SDF Network ; September 2015",
        ))
        .to_array();
    env.ledger().with_mut(|l| l.network_id = net);

    // The account pins the stateless registry id; cross-check it is exactly the
    // name-salt derivation from the perch registry, then use it as the deployer.
    let stateless = Address::from_str(&env, STATELESS_REGISTRY);
    let perch_registry = Address::from_str(&env, PERCH_REGISTRY);
    assert_eq!(stateless, stateless::address(&env, &perch_registry));

    // The account's *actual* pinned compiler + interpreter derive the live ids.
    assert_eq!(
        compiler::address(&env, &stateless),
        Address::from_str(
            &env,
            "CCUU7RYG23ZBZZCKS2PPSZ2GJIBTBYXF47GZCYG5PUBN54Z7AKQBF2SY"
        ),
    );
    assert_eq!(
        interpreter::address(&env, &stateless),
        Address::from_str(
            &env,
            "CBYWKTO6IALDRI7LQM2IBHK7SDKXKO5JTMJCVQVKEI4XMJ724ZVJI2YM"
        ),
    );
    assert_eq!(
        verifier::address(&env, &stateless),
        Address::from_str(
            &env,
            "CBVCTXCSF4HJJCQLLIM543CH5MJW3A2MMZ2T35GSCSN6QSC6BGSDJNNY"
        ),
    );
}
