// GENERATED FILE — do not edit by hand.
//
// TypeScript client bindings for perch-account-factory, generated by
// `stellar contract bindings typescript` from the wasm deployed in
// deployments/testnet.json. Regenerate with scripts/bindings-contracts.sh.

/** sha256 of the wasm these bindings were generated from. */
export const WASM_SHA256 = "82d137c9870a6045e03ee53a5ae5d498f389f48f63c9ac8d046be3c869fa77f1";

import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}





/**
 * Represents different types of signers in the smart account system.
 */
export type Signer = {tag: "Delegated", values: readonly [string]} | {tag: "External", values: readonly [string, Buffer]};

export interface Client {
  /**
   * Construct and simulate a create transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Deploy an account whose constructor installs `admin_signers` as its
   * admin rule. Permissionless. Fails if that account already exists.
   */
  create: ({salt, admin_signers}: {salt: Buffer, admin_signers: Array<Signer>}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a version transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * See [`VERSION`].
   */
  version: (options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a address_of transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The address [`Self::create`] deploys for `salt` and `admin_signers`.
   */
  address_of: ({salt, admin_signers}: {salt: Buffer, admin_signers: Array<Signer>}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a create_passkey transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Deploy an account administered by one passkey, verified by the pinned
   * WebAuthn verifier.
   */
  create_passkey: ({salt, key_data}: {salt: Buffer, key_data: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a passkey_signer transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The admin signer [`Self::create_passkey`] installs for `key_data`
   * (the 65-byte secp256r1 public key, optionally followed by the
   * credential id).
   */
  passkey_signer: ({key_data}: {key_data: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<Signer>>

  /**
   * Construct and simulate a passkey_address transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The address [`Self::create_passkey`] deploys.
   */
  passkey_address: ({salt, key_data}: {salt: Buffer, key_data: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a account_wasm_hash transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The pinned `perch-account` wasm hash every account is deployed from.
   */
  account_wasm_hash: (options?: MethodOptions) => Promise<AssembledTransaction<Buffer>>

  /**
   * Construct and simulate a webauthn_verifier transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The pinned WebAuthn verifier passkey signers name.
   */
  webauthn_verifier: (options?: MethodOptions) => Promise<AssembledTransaction<string>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAABQAAAC5FbWl0dGVkIGZvciBldmVyeSBhY2NvdW50IHRoZSBmYWN0b3J5IGNyZWF0ZXMuAAAAAAAAAAAADkFjY291bnRDcmVhdGVkAAAAAAABAAAAD2FjY291bnRfY3JlYXRlZAAAAAADAAAAAAAAAAdhY2NvdW50AAAAABMAAAABAAAAAAAAAARzYWx0AAAD7gAAACAAAAAAAAAAAAAAAA1hZG1pbl9zaWduZXJzAAAAAAAD6gAAB9AAAAAGU2lnbmVyAAAAAAAAAAAAAg==",
        "AAAAAAAAAIVEZXBsb3kgYW4gYWNjb3VudCB3aG9zZSBjb25zdHJ1Y3RvciBpbnN0YWxscyBgYWRtaW5fc2lnbmVyc2AgYXMgaXRzCmFkbWluIHJ1bGUuIFBlcm1pc3Npb25sZXNzLiBGYWlscyBpZiB0aGF0IGFjY291bnQgYWxyZWFkeSBleGlzdHMuAAAAAAAABmNyZWF0ZQAAAAAAAgAAAAAAAAAEc2FsdAAAA+4AAAAgAAAAAAAAAA1hZG1pbl9zaWduZXJzAAAAAAAD6gAAB9AAAAAGU2lnbmVyAAAAAAABAAAAEw==",
        "AAAAAAAAABBTZWUgW2BWRVJTSU9OYF0uAAAAB3ZlcnNpb24AAAAAAAAAAAEAAAAE",
        "AAAAAAAAAERUaGUgYWRkcmVzcyBbYFNlbGY6OmNyZWF0ZWBdIGRlcGxveXMgZm9yIGBzYWx0YCBhbmQgYGFkbWluX3NpZ25lcnNgLgAAAAphZGRyZXNzX29mAAAAAAACAAAAAAAAAARzYWx0AAAD7gAAACAAAAAAAAAADWFkbWluX3NpZ25lcnMAAAAAAAPqAAAH0AAAAAZTaWduZXIAAAAAAAEAAAAT",
        "AAAAAAAAAFhEZXBsb3kgYW4gYWNjb3VudCBhZG1pbmlzdGVyZWQgYnkgb25lIHBhc3NrZXksIHZlcmlmaWVkIGJ5IHRoZSBwaW5uZWQKV2ViQXV0aG4gdmVyaWZpZXIuAAAADmNyZWF0ZV9wYXNza2V5AAAAAAACAAAAAAAAAARzYWx0AAAD7gAAACAAAAAAAAAACGtleV9kYXRhAAAADgAAAAEAAAAT",
        "AAAAAAAAAI9UaGUgYWRtaW4gc2lnbmVyIFtgU2VsZjo6Y3JlYXRlX3Bhc3NrZXlgXSBpbnN0YWxscyBmb3IgYGtleV9kYXRhYAoodGhlIDY1LWJ5dGUgc2VjcDI1NnIxIHB1YmxpYyBrZXksIG9wdGlvbmFsbHkgZm9sbG93ZWQgYnkgdGhlCmNyZWRlbnRpYWwgaWQpLgAAAAAOcGFzc2tleV9zaWduZXIAAAAAAAEAAAAAAAAACGtleV9kYXRhAAAADgAAAAEAAAfQAAAABlNpZ25lcgAA",
        "AAAAAAAAAC1UaGUgYWRkcmVzcyBbYFNlbGY6OmNyZWF0ZV9wYXNza2V5YF0gZGVwbG95cy4AAAAAAAAPcGFzc2tleV9hZGRyZXNzAAAAAAIAAAAAAAAABHNhbHQAAAPuAAAAIAAAAAAAAAAIa2V5X2RhdGEAAAAOAAAAAQAAABM=",
        "AAAAAAAAAERUaGUgcGlubmVkIGBwZXJjaC1hY2NvdW50YCB3YXNtIGhhc2ggZXZlcnkgYWNjb3VudCBpcyBkZXBsb3llZCBmcm9tLgAAABFhY2NvdW50X3dhc21faGFzaAAAAAAAAAAAAAABAAAD7gAAACA=",
        "AAAAAAAAADJUaGUgcGlubmVkIFdlYkF1dGhuIHZlcmlmaWVyIHBhc3NrZXkgc2lnbmVycyBuYW1lLgAAAAAAEXdlYmF1dGhuX3ZlcmlmaWVyAAAAAAAAAAAAAAEAAAAT",
        "AAAAAgAAAEJSZXByZXNlbnRzIGRpZmZlcmVudCB0eXBlcyBvZiBzaWduZXJzIGluIHRoZSBzbWFydCBhY2NvdW50IHN5c3RlbS4AAAAAAAAAAAAGU2lnbmVyAAAAAAACAAAAAQAAAD1BIGRlbGVnYXRlZCBzaWduZXIgdGhhdCB1c2VzIGJ1aWx0LWluIHNpZ25hdHVyZSB2ZXJpZmljYXRpb24uAAAAAAAACURlbGVnYXRlZAAAAAAAAAEAAAATAAAAAQAAAHJBbiBleHRlcm5hbCBzaWduZXIgd2l0aCBjdXN0b20gdmVyaWZpY2F0aW9uIGxvZ2ljLgpDb250YWlucyB0aGUgdmVyaWZpZXIgY29udHJhY3QgYWRkcmVzcyBhbmQgdGhlIHB1YmxpYyBrZXkgZGF0YS4AAAAAAAhFeHRlcm5hbAAAAAIAAAATAAAADg==" ]),
      options
    )
  }
  public readonly fromJSON = {
    create: this.txFromJSON<string>,
        version: this.txFromJSON<u32>,
        address_of: this.txFromJSON<string>,
        create_passkey: this.txFromJSON<string>,
        passkey_signer: this.txFromJSON<Signer>,
        passkey_address: this.txFromJSON<string>,
        account_wasm_hash: this.txFromJSON<Buffer>,
        webauthn_verifier: this.txFromJSON<string>
  }
}