// GENERATED FILE — do not edit by hand.
//
// TypeScript client bindings for perch-webauthn-verifier, generated by
// `stellar contract bindings typescript` from the wasm deployed in
// deployments/testnet.json. Regenerate with scripts/bindings-contracts.sh.

/** sha256 of the wasm these bindings were generated from. */
export const WASM_SHA256 = "9e9fbe7886d9bb149a6e3ee10de15954c57bbdf20f817ed94e1370c01b9c669e";

import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}




/**
 * Error types for WebAuthn verification operations.
 */
export const WebAuthnError = {
  /**
   * The signature payload is invalid or has incorrect format.
   */
  3110: {message:"SignaturePayloadInvalid"},
  /**
   * The client data exceeds the maximum allowed length.
   */
  3111: {message:"ClientDataTooLong"},
  /**
   * Failed to parse JSON from client data.
   */
  3112: {message:"JsonParseError"},
  /**
   * The type field in client data is not "webauthn.get".
   */
  3113: {message:"TypeFieldInvalid"},
  /**
   * The challenge in client data does not match expected value.
   */
  3114: {message:"ChallengeInvalid"},
  /**
   * The authenticator data format is invalid or too short.
   */
  3115: {message:"AuthDataFormatInvalid"},
  /**
   * The User Present (UP) bit is not set in authenticator flags.
   */
  3116: {message:"PresentBitNotSet"},
  /**
   * The User Verified (UV) bit is not set in authenticator flags.
   */
  3117: {message:"VerifiedBitNotSet"},
  /**
   * Invalid relationship between Backup Eligibility and State bits.
   */
  3118: {message:"BackupEligibilityAndStateNotSet"},
  /**
   * The provided key data does not contain a valid 65-byte public key.
   */
  3119: {message:"KeyDataInvalid"}
}

export interface Client {
  /**
   * Construct and simulate a verify transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Whether `sig_data` (XDR `WebAuthnSigData`) is a valid assertion over
   * `signature_payload` by the key in `key_data`. Malformed data traps
   * rather than returning `false`, like OZ's verifier does.
   */
  verify: ({signature_payload, key_data, sig_data}: {signature_payload: Buffer, key_data: Buffer, sig_data: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<boolean>>

  /**
   * Construct and simulate a canonicalize_key transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The 65-byte public key, without any credential-id suffix: the
   * identity OZ uses to detect duplicate signers, and the compiler uses to
   * fingerprint credentials.
   */
  canonicalize_key: ({key_data}: {key_data: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<Buffer>>

  /**
   * Construct and simulate a batch_canonicalize_key transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  batch_canonicalize_key: ({key_data}: {key_data: Array<Buffer>}, options?: MethodOptions) => Promise<AssembledTransaction<Array<Buffer>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAAL9XaGV0aGVyIGBzaWdfZGF0YWAgKFhEUiBgV2ViQXV0aG5TaWdEYXRhYCkgaXMgYSB2YWxpZCBhc3NlcnRpb24gb3Zlcgpgc2lnbmF0dXJlX3BheWxvYWRgIGJ5IHRoZSBrZXkgaW4gYGtleV9kYXRhYC4gTWFsZm9ybWVkIGRhdGEgdHJhcHMKcmF0aGVyIHRoYW4gcmV0dXJuaW5nIGBmYWxzZWAsIGxpa2UgT1oncyB2ZXJpZmllciBkb2VzLgAAAAAGdmVyaWZ5AAAAAAADAAAAAAAAABFzaWduYXR1cmVfcGF5bG9hZAAAAAAAAA4AAAAAAAAACGtleV9kYXRhAAAADgAAAAAAAAAIc2lnX2RhdGEAAAAOAAAAAQAAAAE=",
        "AAAAAAAAAJ1UaGUgNjUtYnl0ZSBwdWJsaWMga2V5LCB3aXRob3V0IGFueSBjcmVkZW50aWFsLWlkIHN1ZmZpeDogdGhlCmlkZW50aXR5IE9aIHVzZXMgdG8gZGV0ZWN0IGR1cGxpY2F0ZSBzaWduZXJzLCBhbmQgdGhlIGNvbXBpbGVyIHVzZXMgdG8KZmluZ2VycHJpbnQgY3JlZGVudGlhbHMuAAAAAAAAEGNhbm9uaWNhbGl6ZV9rZXkAAAABAAAAAAAAAAhrZXlfZGF0YQAAAA4AAAABAAAADg==",
        "AAAAAAAAAAAAAAAWYmF0Y2hfY2Fub25pY2FsaXplX2tleQAAAAAAAQAAAAAAAAAIa2V5X2RhdGEAAAPqAAAADgAAAAEAAAPqAAAADg==",
        "AAAABAAAADFFcnJvciB0eXBlcyBmb3IgV2ViQXV0aG4gdmVyaWZpY2F0aW9uIG9wZXJhdGlvbnMuAAAAAAAAAAAAAA1XZWJBdXRobkVycm9yAAAAAAAACgAAADlUaGUgc2lnbmF0dXJlIHBheWxvYWQgaXMgaW52YWxpZCBvciBoYXMgaW5jb3JyZWN0IGZvcm1hdC4AAAAAAAAXU2lnbmF0dXJlUGF5bG9hZEludmFsaWQAAAAMJgAAADNUaGUgY2xpZW50IGRhdGEgZXhjZWVkcyB0aGUgbWF4aW11bSBhbGxvd2VkIGxlbmd0aC4AAAAAEUNsaWVudERhdGFUb29Mb25nAAAAAAAMJwAAACZGYWlsZWQgdG8gcGFyc2UgSlNPTiBmcm9tIGNsaWVudCBkYXRhLgAAAAAADkpzb25QYXJzZUVycm9yAAAAAAwoAAAANFRoZSB0eXBlIGZpZWxkIGluIGNsaWVudCBkYXRhIGlzIG5vdCAid2ViYXV0aG4uZ2V0Ii4AAAAQVHlwZUZpZWxkSW52YWxpZAAADCkAAAA7VGhlIGNoYWxsZW5nZSBpbiBjbGllbnQgZGF0YSBkb2VzIG5vdCBtYXRjaCBleHBlY3RlZCB2YWx1ZS4AAAAAEENoYWxsZW5nZUludmFsaWQAAAwqAAAANlRoZSBhdXRoZW50aWNhdG9yIGRhdGEgZm9ybWF0IGlzIGludmFsaWQgb3IgdG9vIHNob3J0LgAAAAAAFUF1dGhEYXRhRm9ybWF0SW52YWxpZAAAAAAADCsAAAA8VGhlIFVzZXIgUHJlc2VudCAoVVApIGJpdCBpcyBub3Qgc2V0IGluIGF1dGhlbnRpY2F0b3IgZmxhZ3MuAAAAEFByZXNlbnRCaXROb3RTZXQAAAwsAAAAPVRoZSBVc2VyIFZlcmlmaWVkIChVVikgYml0IGlzIG5vdCBzZXQgaW4gYXV0aGVudGljYXRvciBmbGFncy4AAAAAAAARVmVyaWZpZWRCaXROb3RTZXQAAAAAAAwtAAAAP0ludmFsaWQgcmVsYXRpb25zaGlwIGJldHdlZW4gQmFja3VwIEVsaWdpYmlsaXR5IGFuZCBTdGF0ZSBiaXRzLgAAAAAfQmFja3VwRWxpZ2liaWxpdHlBbmRTdGF0ZU5vdFNldAAAAAwuAAAAQlRoZSBwcm92aWRlZCBrZXkgZGF0YSBkb2VzIG5vdCBjb250YWluIGEgdmFsaWQgNjUtYnl0ZSBwdWJsaWMga2V5LgAAAAAADktleURhdGFJbnZhbGlkAAAAAAwv" ]),
      options
    )
  }
  public readonly fromJSON = {
    verify: this.txFromJSON<boolean>,
        canonicalize_key: this.txFromJSON<Buffer>,
        batch_canonicalize_key: this.txFromJSON<Array<Buffer>>
  }
}